import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight, Clock3, Eye } from "lucide-react";
import type { Blog } from "@/types/blog.types";

function name(value: Blog["author"] | Blog["category"], fallback: string) { return typeof value === "string" ? fallback : value?.name || fallback; }

export default function FeaturedBlogs({ blog }: { blog?: Blog }) {
  if (!blog) return null;
  const image = blog.featuredImage?.url;
  return <section className="mx-auto max-w-7xl px-5 py-14 sm:px-8 lg:px-10 lg:py-20"><div className="mb-7 flex items-end justify-between"><div><p className="text-sm font-semibold text-violet-600 dark:text-violet-400">Editor&apos;s pick</p><h2 className="landing-featured-heading mt-1 text-2xl font-bold text-slate-900 dark:text-white">A story worth your time</h2></div><Link href={`/blogs/${blog._id}`} className="hidden items-center gap-2 text-sm font-semibold text-violet-600 hover:text-violet-500 dark:text-violet-400 sm:inline-flex">Read feature <ArrowUpRight className="h-4 w-4" /></Link></div><Link href={`/blogs/${blog._id}`} className="landing-featured-card group grid overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl dark:border-slate-800 dark:bg-slate-900 lg:grid-cols-[1.15fr_0.85fr]"><div className="relative min-h-[280px] bg-slate-100 dark:bg-slate-800">{image ? <Image src={image} alt={blog.featuredImage?.alt || blog.title} fill sizes="(max-width: 1024px) 100vw, 65vw" className="object-cover transition duration-700 group-hover:scale-105" /> : <div className="flex h-full items-end bg-gradient-to-br from-violet-200 to-indigo-100 p-8 text-violet-700 dark:from-violet-950 dark:to-indigo-950 dark:text-violet-300">Featured story</div>}</div><div className="flex flex-col justify-center p-7 sm:p-10"><div className="flex flex-wrap items-center gap-3 text-xs font-semibold uppercase tracking-[0.12em] text-violet-600 dark:text-violet-400"><span>{name(blog.category, "Blog")}</span><span className="h-1 w-1 rounded-full bg-violet-400" /><span>{new Date(blog.publishedAt || blog.createdAt).toLocaleDateString("en-IN")}</span></div><h3 className="landing-featured-title mt-5 text-3xl font-bold leading-tight text-slate-900 transition group-hover:text-violet-600 dark:text-white dark:group-hover:text-violet-400">{blog.title}</h3><p className="mt-4 line-clamp-3 text-sm leading-7 text-slate-600 dark:text-slate-300">{blog.description}</p><div className="mt-7 flex flex-wrap items-center gap-4 text-xs text-slate-500 dark:text-slate-400"><span className="font-medium text-slate-700 dark:text-slate-200">{name(blog.author, "GolpoKotha author")}</span><span className="inline-flex items-center gap-1"><Clock3 className="h-3.5 w-3.5" /> {blog.readingTime || 5} min read</span><span className="inline-flex items-center gap-1"><Eye className="h-3.5 w-3.5" /> {(blog.views || 0).toLocaleString()}</span></div></div></Link></section>;
}
