import Link from "next/link";
import { ArrowDown, ArrowRight, BookOpen, Sparkles } from "lucide-react";

export default function HeroSection() {
  return (
    <section className="landing-hero relative overflow-hidden border-b border-slate-200/80 bg-gradient-to-br from-violet-50 via-white to-indigo-50 dark:border-slate-800 dark:from-violet-950/30 dark:via-slate-950 dark:to-indigo-950/20">
      <div className="pointer-events-none absolute -right-24 -top-24 h-72 w-72 rounded-full bg-violet-200/50 blur-3xl dark:bg-violet-700/20" />
      <div className="relative mx-auto grid max-w-7xl gap-12 px-5 py-20 sm:px-8 lg:grid-cols-[1.05fr_0.95fr] lg:items-center lg:px-10 lg:py-28">
        <div className="max-w-3xl"><span className="landing-hero-eyebrow inline-flex items-center gap-2 rounded-full bg-violet-50 px-3 py-1.5 text-xs font-semibold uppercase tracking-[0.16em] text-violet-600 dark:bg-violet-950/50 dark:text-violet-400"><Sparkles className="h-3.5 w-3.5" /> Discover ideas that matter</span><h1 className="mt-6 text-5xl font-bold leading-[1.02] tracking-tight text-slate-950 sm:text-7xl dark:text-white">A better place for <span className="text-violet-600 dark:text-violet-400">thoughtful</span> reading.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600 dark:text-slate-300">Read stories from curious minds, discover fresh perspectives, and build a reading life that feels like your own.</p><div className="mt-8 flex flex-wrap items-center gap-3"><a href="#explore" className="inline-flex items-center gap-2 rounded-xl bg-violet-600 px-5 py-3 text-sm font-semibold text-white shadow-lg shadow-violet-600/20 transition hover:bg-violet-500">Explore blogs <ArrowRight className="h-4 w-4" /></a><Link href="/register" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-5 py-3 text-sm font-semibold text-slate-700 transition hover:border-violet-300 hover:text-violet-600 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200 dark:hover:border-violet-500 dark:hover:text-violet-400">Join the community</Link></div><div className="landing-reading-note mt-6 inline-flex items-center gap-3 rounded-2xl border border-slate-200 bg-white/70 px-4 py-3 shadow-sm dark:border-slate-700 dark:bg-slate-900/70"><span className="landing-reading-icon flex h-9 w-9 items-center justify-center rounded-xl bg-violet-50 text-violet-600 dark:bg-violet-950/60 dark:text-violet-400"><BookOpen className="h-4 w-4" /></span><span><strong className="landing-reading-title block text-sm font-semibold text-slate-800 dark:text-slate-100">Read freely</strong><span className="landing-reading-copy text-xs text-slate-500 dark:text-slate-400">Join to like, comment, and save.</span></span></div></div>
        <div className="relative hidden min-h-[310px] items-center justify-center lg:flex"><div className="relative h-72 w-80"><div className="absolute left-1/2 top-8 h-64 w-64 -translate-x-1/2 rounded-[2rem] bg-violet-600 shadow-2xl shadow-violet-900/20 rotate-[-8deg]" /><div className="landing-hero-card absolute left-1/2 top-3 h-64 w-64 -translate-x-1/2 rounded-[2rem] border border-white/60 bg-white/80 p-7 shadow-xl backdrop-blur dark:border-slate-700 dark:bg-slate-900/80 rotate-[6deg]"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-violet-600 dark:text-violet-400">Your next read</p><p className="mt-10 text-3xl font-bold leading-tight text-slate-900 dark:text-white">Stories that stay with you.</p><div className="mt-8 flex items-center gap-2 text-sm text-slate-500 dark:text-slate-400"><ArrowDown className="h-4 w-4 text-violet-500" /> Begin exploring</div></div></div></div>
      </div>
    </section>
  );
}
